# Closed trade history — Bybit (last N days, M5)

Fetches **closed P&L** for `SYMBOLS`, saves `./data/<SYMBOL>/trades/closed_pnl_history.csv`, and draws **one chart per symbol**: **M5 close** over the last **5 days** (default), with entry / exit markers and dashed connectors.

**Params:** `BYBIT_TRADE_LOOKBACK_DAYS` (default `5`), `BYBIT_TRADE_CHART_INTERVAL` (default `5` = M5). Bybit closed-PnL requests use at most a **7-day** `startTime`–`endTime` range per call; longer lookbacks are stepped in slices. Platform max history (~2 years) is still capped via `BYBIT_CLOSED_PNL_PLATFORM_CAP_DAYS` if you raise the lookback.

Requires `.env` with API keys; use **`BYBIT_DEMO=true`** for Demo Trading (`api-demo.bybit.com`).

In [93]:
# %pip install plotly nbformat --quiet

In [94]:
# SECTION 1 — Imports, symbols, paths
import warnings
warnings.filterwarnings("ignore")

import os
import sys
import time
import hashlib
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display

_ROOT = Path.cwd().resolve()
if _ROOT.name == "notebooks":
    _ROOT = _ROOT.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

try:
    from dotenv import load_dotenv
    _env = _ROOT / ".env"
    if _env.exists():
        load_dotenv(_env)
        print(f"Loaded .env from {_env}")
    else:
        print(f"No .env at {_env}")
except ImportError:
    print("python-dotenv not installed")

SYMBOLS = [ "XLMUSDT",   "BTCUSDT","BCHUSDT","ETHUSDT","BNBUSDT","XRPUSDT","ADAUSDT","SOLUSDT","DOGEUSDT","DOTUSDT","AVAXUSDT","SHIB1000USDT","LTCUSDT", ]

# SYMBOLS = [
#     "BTCUSDT", "XRPUSDT", "ETHUSDT", "BNBUSDT", "ADAUSDT", "SOLUSDT", "DOGEUSDT",
#     "DOTUSDT", "AVAXUSDT", "BCHUSDT", "SHIB1000USDT", "LTCUSDT", "XLMUSDT",
# ]

CATEGORY = "linear"
TESTNET = os.getenv("BYBIT_TESTNET", "false").lower() == "true"
DEMO = os.getenv("BYBIT_DEMO", "true").lower() == "true"

LOOKBACK_DAYS = int(os.getenv("BYBIT_TRADE_LOOKBACK_DAYS", "8"))
CLOSED_PNL_CAP_DAYS = int(os.getenv("BYBIT_CLOSED_PNL_PLATFORM_CAP_DAYS", "719"))
EFFECTIVE_CLOSED_PNL_DAYS = min(LOOKBACK_DAYS, CLOSED_PNL_CAP_DAYS)

CHART_INTERVAL = os.getenv("BYBIT_TRADE_CHART_INTERVAL", "5")

_TEHRAN = "Asia/Tehran"
BASE_DIR = Path("./data")

_mode = "demo" if DEMO else ("testnet" if TESTNET else "mainnet")
if DEMO and TESTNET:
    raise ValueError("Use only one of BYBIT_DEMO or BYBIT_TESTNET")

print(f"Symbols: {SYMBOLS}")
print(f"Endpoint: {_mode}  |  M{CHART_INTERVAL} chart  |  lookback {LOOKBACK_DAYS}d")

Loaded .env from D:\bot\ema-h1trend-exchange\.env
Symbols: ['XLMUSDT', 'BTCUSDT', 'BCHUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'ADAUSDT', 'SOLUSDT', 'DOGEUSDT', 'DOTUSDT', 'AVAXUSDT', 'SHIB1000USDT', 'LTCUSDT']
Endpoint: demo  |  M5 chart  |  lookback 8d

In [95]:
# SECTION 2 — Bybit client
from pybit.unified_trading import HTTP

api_key = os.getenv("BYBIT_API_KEY", "")
api_secret = os.getenv("BYBIT_API_SECRET", "")

client = HTTP(
    testnet=TESTNET,
    demo=DEMO,
    api_key=api_key or None,
    api_secret=api_secret or None,
)

print(f"HTTP demo={DEMO} testnet={TESTNET}  |  API key set: {bool(api_key)}")

HTTP demo=True testnet=False  |  API key set: True

In [96]:
# SECTION 3 — Fetch helpers

SEVEN_MS = 7 * 24 * 60 * 60 * 1000
DAY_MS = 24 * 60 * 60 * 1000

_SL_TYPES = {"StopLoss", "Stop", "OcoTriggerByStopLoss"}
_TP_TYPES = {"TakeProfit", "OcoTriggerByTp"}


def _dedupe_key(row: dict) -> str:
    raw = "|".join(
        str(row.get(k, ""))
        for k in ("orderId", "symbol", "updatedTime", "closedSize", "avgExitPrice", "closedPnl")
    )
    return hashlib.sha256(raw.encode()).hexdigest()


def fetch_closed_pnl_all_history(symbol: str) -> list[dict]:
    now_ms = int(time.time() * 1000)
    boundary = now_ms - EFFECTIVE_CLOSED_PNL_DAYS * DAY_MS
    out: list[dict] = []
    seen: set[str] = set()

    window_end = now_ms
    while window_end > boundary:
        window_start = max(window_end - SEVEN_MS, boundary)
        cursor = None
        while True:
            kwargs = dict(
                category=CATEGORY, symbol=symbol, limit=100,
                startTime=str(window_start), endTime=str(window_end),
            )
            if cursor:
                kwargs["cursor"] = cursor

            resp = client.get_closed_pnl(**kwargs)
            if resp.get("retCode") != 0:
                raise RuntimeError(f"Bybit {resp.get('retCode')}: {resp.get('retMsg')}")

            result = resp["result"]
            items = result.get("list") or []
            for row in items:
                k = _dedupe_key(row)
                if k not in seen:
                    seen.add(k)
                    out.append(row)

            cursor = result.get("nextPageCursor") or ""
            if not cursor or not items:
                break
            time.sleep(0.06)

        window_end = window_start - 1
        time.sleep(0.06)

    return out


def closed_pnl_rows_to_dataframe(rows: list[dict]) -> pd.DataFrame:
    if not rows:
        return pd.DataFrame()
    df = pd.DataFrame(rows)
    for col in ("createdTime", "updatedTime", "createdAt", "updatedAt"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    t_entry_col = "createdTime" if "createdTime" in df.columns else "createdAt"
    t_exit_col  = "updatedTime" if "updatedTime" in df.columns else "updatedAt"
    if t_entry_col not in df.columns or t_exit_col not in df.columns:
        raise ValueError(f"Unexpected columns: {list(df.columns)}")

    df["entry_time"] = pd.to_datetime(df[t_entry_col], unit="ms", utc=True)
    df["exit_time"]  = pd.to_datetime(df[t_exit_col],  unit="ms", utc=True)
    for col in ("avgEntryPrice", "avgExitPrice", "closedPnl", "closedSize"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "side" in df.columns:
        df["position"] = df["side"].map({"Buy": "Short", "Sell": "Long"}).fillna(df["side"])

    df = df.sort_values("exit_time").reset_index(drop=True)
    return df


def fetch_klines_in_range(symbol: str, interval: str, start_ms: int, end_ms: int) -> pd.DataFrame:
    all_rows: list[list] = []
    cur_end = int(end_ms)
    MAX_RETRIES = 5

    while cur_end >= start_ms:
        kwargs = dict(category=CATEGORY, symbol=symbol, interval=interval, limit=1000, end=cur_end)
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                resp = client.get_kline(**kwargs)
                if resp.get("retCode") != 0:
                    raise RuntimeError(resp.get("retMsg"))
                rows = resp["result"].get("list", [])
                break
            except Exception:
                if attempt == MAX_RETRIES:
                    raise
                time.sleep(2 ** attempt)

        if not rows:
            break
        all_rows.extend(rows)
        oldest = int(rows[-1][0])
        if oldest <= start_ms or len(rows) < 1000:
            break
        cur_end = oldest - 1
        time.sleep(0.05)

    if not all_rows:
        return pd.DataFrame(columns=["open", "high", "low", "close", "volume"])

    df = pd.DataFrame(
        list(reversed(all_rows)),
        columns=["time", "open", "high", "low", "close", "volume", "turnover"],
    )
    df["time"] = pd.to_datetime(df["time"].astype("int64"), unit="ms", utc=True)
    df = df.set_index("time").sort_index()
    df = df[~df.index.duplicated(keep="last")]
    for col in ("open", "high", "low", "close", "volume"):
        df[col] = df[col].astype(float)

    start_dt = pd.to_datetime(start_ms, unit="ms", utc=True)
    end_dt   = pd.to_datetime(end_ms,   unit="ms", utc=True)
    return df.loc[(df.index >= start_dt) & (df.index <= end_dt),
                  ["open", "high", "low", "close", "volume"]]


def _classify_exit(row: pd.Series) -> str:
    sot = str(row.get("stopOrderType", "") or "").strip()
    if sot in _SL_TYPES:
        return "SL"
    if sot in _TP_TYPES:
        return "TP"
    try:
        return "SL" if float(row.get("closedPnl", 0)) < 0 else "TP"
    except (TypeError, ValueError):
        return "manual"


def compute_rsi(close: pd.Series, period: int = 21) -> pd.Series:
    delta = close.diff()
    gain = delta.clip(lower=0).rolling(window=period).mean()
    loss = (-delta.clip(upper=0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - 100 / (1 + rs)


def plot_symbol_trades(symbol: str, ohlcv: pd.DataFrame, trades: pd.DataFrame) -> None:
    fig = make_subplots(
        rows=2, cols=1,
        shared_xaxes=True,
        row_heights=[0.72, 0.28],
        vertical_spacing=0.04,
        subplot_titles=("", "RSI (14)"),
    )

    # Candlestick — row 1
    if not ohlcv.empty:
        fig.add_trace(go.Candlestick(
            x=ohlcv.index,
            open=ohlcv["open"], high=ohlcv["high"],
            low=ohlcv["low"],  close=ohlcv["close"],
            name="Price",
            increasing_line_color="#26a69a",
            decreasing_line_color="#ef5350",
            hovertext=[
                f"O: {o:.4f}  H: {h:.4f}  L: {l:.4f}  C: {c:.4f}"
                for o, h, l, c in zip(ohlcv["open"], ohlcv["high"], ohlcv["low"], ohlcv["close"])
            ],
            hoverinfo="x+text",
        ), row=1, col=1)

    if not trades.empty:
        trades = trades.copy()
        trades["_exit_type"] = trades.apply(_classify_exit, axis=1)
        et = trades["entry_time"].dt.tz_convert(_TEHRAN)
        xt = trades["exit_time"].dt.tz_convert(_TEHRAN)

        # Dashed connectors
        for i in range(len(trades)):
            fig.add_trace(go.Scatter(
                x=[et.iloc[i], xt.iloc[i]],
                y=[float(trades["avgEntryPrice"].iloc[i]), float(trades["avgExitPrice"].iloc[i])],
                mode="lines",
                line=dict(color="rgba(150,150,150,0.5)", width=1, dash="dash"),
                showlegend=False, hoverinfo="skip",
            ), row=1, col=1)

        pos_col = trades["position"].tolist()  if "position"  in trades.columns else [""] * len(trades)
        ord_col = trades["orderType"].tolist() if "orderType" in trades.columns else [""] * len(trades)
        fig.add_trace(go.Scatter(
            x=et, y=trades["avgEntryPrice"],
            mode="markers", name="Entry",
            marker=dict(symbol="triangle-up", color="royalblue", size=13),
            customdata=list(zip(trades["avgEntryPrice"].round(4), pos_col, ord_col)),
            hovertemplate=(
                "<b>Entry</b><br>"
                "Time: %{x}<br>"
                "Price: %{customdata[0]}<br>"
                "Position: %{customdata[1]}<br>"
                "OrderType: %{customdata[2]}"
                "<extra></extra>"
            ),
        ), row=1, col=1)

        sl_mask = trades["_exit_type"] == "SL"
        sl_t = trades[sl_mask]
        if len(sl_t):
            fig.add_trace(go.Scatter(
                x=xt[sl_mask], y=sl_t["avgExitPrice"],
                mode="markers", name="Exit SL",
                marker=dict(symbol="x", color="firebrick", size=13,
                            line=dict(width=2.5, color="firebrick")),
                customdata=list(zip(sl_t["avgExitPrice"].round(4), sl_t["closedPnl"].round(4))),
                hovertemplate=(
                    "<b>Exit — Stop Loss</b><br>"
                    "Time: %{x}<br>"
                    "Price: %{customdata[0]}<br>"
                    "PnL: %{customdata[1]}"
                    "<extra></extra>"
                ),
            ), row=1, col=1)

        tp_mask = trades["_exit_type"] == "TP"
        tp_t = trades[tp_mask]
        if len(tp_t):
            fig.add_trace(go.Scatter(
                x=xt[tp_mask], y=tp_t["avgExitPrice"],
                mode="markers", name="Exit TP",
                marker=dict(symbol="circle", color="seagreen", size=12),
                customdata=list(zip(tp_t["avgExitPrice"].round(4), tp_t["closedPnl"].round(4))),
                hovertemplate=(
                    "<b>Exit — Take Profit</b><br>"
                    "Time: %{x}<br>"
                    "Price: %{customdata[0]}<br>"
                    "PnL: %{customdata[1]}"
                    "<extra></extra>"
                ),
            ), row=1, col=1)

    # RSI — row 2
    if not ohlcv.empty:
        rsi = compute_rsi(ohlcv["close"])
        fig.add_trace(go.Scatter(
            x=ohlcv.index, y=rsi,
            mode="lines", name="RSI(14)",
            line=dict(color="#b388ff", width=1.5),
            hovertemplate="RSI: %{y:.2f}<extra></extra>",
        ), row=2, col=1)
        # overbought / oversold bands
        fig.add_hrect(y0=70, y1=100, fillcolor="rgba(239,83,80,0.08)", line_width=0, row=2, col=1)
        fig.add_hrect(y0=0,  y1=30,  fillcolor="rgba(38,166,154,0.08)", line_width=0, row=2, col=1)
        fig.add_hline(y=70, line=dict(color="rgba(239,83,80,0.55)", width=1, dash="dot"), row=2, col=1)
        fig.add_hline(y=30, line=dict(color="rgba(38,166,154,0.55)", width=1, dash="dot"), row=2, col=1)

    fig.update_layout(
        title=f"{symbol}  |  last {LOOKBACK_DAYS}d  M{CHART_INTERVAL}  |  closed trades: {len(trades)}",
        hovermode="x unified",
        height=700,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        xaxis=dict(
            rangeslider=dict(visible=False),
            rangeselector=dict(buttons=[
                dict(count=6,  label="6h",  step="hour", stepmode="backward"),
                dict(count=1,  label="1D",  step="day",  stepmode="backward"),
                dict(count=3,  label="3D",  step="day",  stepmode="backward"),
                dict(step="all", label="All"),
            ]),
            type="date",
        ),
        xaxis2=dict(type="date"),
        yaxis=dict(title="Price"),
        yaxis2=dict(title="RSI", range=[0, 100], fixedrange=True),
        margin=dict(t=80, b=20),
    )
    display(fig)


print("Helpers ready.")

Helpers ready.

In [97]:
# SECTION 4 — Download closed P&L for every symbol and save CSV
trade_frames: dict[str, pd.DataFrame] = {}

for symbol in SYMBOLS:
    print(f"Fetching closed P&L: {symbol} ...")
    try:
        rows = fetch_closed_pnl_all_history(symbol)
        df = closed_pnl_rows_to_dataframe(rows)
        trade_frames[symbol] = df
        out_dir = BASE_DIR / symbol / "trades"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_csv = out_dir / "closed_pnl_history.csv"
        df.to_csv(out_csv, index=False)
        print(f"  -> {len(df)} rows  saved {out_csv}")
    except Exception as exc:
        print(f"  FAILED: {exc}")
        trade_frames[symbol] = pd.DataFrame()

print("Done fetching.")

Fetching closed P&L: XLMUSDT ...
  -> 2 rows  saved data\XLMUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: BTCUSDT ...
  -> 0 rows  saved data\BTCUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: BCHUSDT ...
  -> 3 rows  saved data\BCHUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: ETHUSDT ...
  -> 3 rows  saved data\ETHUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: BNBUSDT ...
  -> 0 rows  saved data\BNBUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: XRPUSDT ...
  -> 4 rows  saved data\XRPUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: ADAUSDT ...
  -> 20 rows  saved data\ADAUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: SOLUSDT ...
  -> 19 rows  saved data\SOLUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: DOGEUSDT ...
  -> 17 rows  saved data\DOGEUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: DOTUSDT ...
  -> 8 rows  saved data\DOTUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: AVAXUSDT ...
  -> 25 rows  saved data\AVAXUSDT\trades\closed_pnl_history.csv
Fetching closed P&L: SHIB1000USDT ...
  -> 12 rows  saved data\SHIB1000USDT\trades\closed_pnl_history.csv
Fetching closed P&L: LTCUSDT ...
  -> 2 rows  saved data\LTCUSDT\trades\closed_pnl_history.csv
Done fetching.

In [98]:
# SECTION 4b — Per-trade leverage, margin & profit % (ROI)
# Bybit closed-PnL rows already carry `leverage` and `cumEntryValue` (entry notional).
# From them we derive, per trade:
#   notional_usdt  = cumEntryValue                    (position size in USDT)
#   margin_usdt    = notional_usdt / leverage         (USDT you actually committed)
#   roi_pct        = closedPnl / margin_usdt * 100    <- "profit % of the trade" (return on margin)
#   price_move_pct = closedPnl / notional_usdt * 100  (return on notional ~ raw price move incl. fees)
# With leverage = 1, roi_pct == price_move_pct. Higher leverage multiplies roi_pct.

def enrich_trade_frame(df: pd.DataFrame) -> pd.DataFrame:
    if df is None or df.empty or "closedPnl" not in df.columns:
        return df
    df = df.copy()
    for col in ("leverage", "cumEntryValue", "cumExitValue", "openFee", "closeFee", "closedPnl"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "leverage" in df.columns:
        lev = df["leverage"].fillna(1.0)
        lev = lev.where(lev > 0, 1.0)
    else:
        lev = pd.Series(1.0, index=df.index)

    if "cumEntryValue" in df.columns and df["cumEntryValue"].notna().any():
        notional = df["cumEntryValue"].fillna(df["avgEntryPrice"] * df["closedSize"])
    else:
        notional = df["avgEntryPrice"] * df["closedSize"]

    margin = notional / lev
    df["leverage"]       = lev
    df["notional_usdt"]  = notional.round(4)
    df["margin_usdt"]    = margin.round(4)
    df["roi_pct"]        = (df["closedPnl"] / margin * 100).round(3)
    df["price_move_pct"] = (df["closedPnl"] / notional * 100).round(3)
    return df

# Enrich every frame and re-save so the CSVs carry the derived columns too.
for _sym, _df in list(trade_frames.items()):
    _e = enrich_trade_frame(_df)
    trade_frames[_sym] = _e
    if _e is not None and not _e.empty:
        _e.to_csv(BASE_DIR / _sym / "trades" / "closed_pnl_history.csv", index=False)

# Per-trade preview (most recent 12 across all symbols)
_all = [d for d in trade_frames.values() if d is not None and not d.empty]
if _all:
    _peek = pd.concat(_all, ignore_index=True).sort_values("exit_time")
    _cols = ["symbol", "position", "leverage", "margin_usdt", "notional_usdt",
             "closedPnl", "roi_pct", "price_move_pct"]
    _cols = [c for c in _cols if c in _peek.columns]
    with pd.option_context("display.max_columns", None, "display.width", 220):
        print("Last 12 trades (per-trade leverage & profit %):")
        print(_peek[_cols].tail(12).to_string(index=False))
else:
    print("No trades to enrich.")

Last 12 trades (per-trade leverage & profit %):
  symbol position  leverage  margin_usdt  notional_usdt  closedPnl  roi_pct  price_move_pct
 LTCUSDT    Short         1     474.0260       474.0260  49.185692   10.376          10.376
AVAXUSDT    Short         1     729.3305       729.3305  49.481999    6.785           6.785
 ADAUSDT    Short         1     480.2247       480.2247  50.266382   10.467          10.467
 ETHUSDT    Short         1     372.5757       372.5757  41.964783   11.263          11.263
 BCHUSDT    Short         1     403.6840       403.6840  38.765718    9.603           9.603
 ADAUSDT    Short         1     818.0522       818.0522 -21.702510   -2.653          -2.653
 SOLUSDT    Short         1     811.9100       811.9100  49.852832    6.140           6.140
 ADAUSDT    Short         1     848.3189       848.3189 -21.070445   -2.484          -2.484
DOGEUSDT    Short         1     682.8224       682.8224  50.650631    7.418           7.418
DOGEUSDT    Short         1     469.4684       469.4684 -19.591001   -4.173          -4.173
 ADAUSDT    Short         1     789.3876       789.3876 -20.786767   -2.633          -2.633
 ADAUSDT    Short         1     604.7017       604.7017 -21.055180   -3.482          -3.482

In [99]:
# SECTION 4c — Inspect enriched trade fields (leverage, margin, ROI)
_debug_sym = next((s for s, d in trade_frames.items()
                   if d is not None and not d.empty), None)
if _debug_sym:
    _df = trade_frames[_debug_sym]
    show_cols = [c for c in [
        "entry_time", "exit_time", "position", "leverage",
        "avgEntryPrice", "avgExitPrice", "notional_usdt", "margin_usdt",
        "closedPnl", "roi_pct", "price_move_pct", "orderType", "stopOrderType",
    ] if c in _df.columns]
    print(f"{_debug_sym}  columns: {list(_df.columns)}\n")
    with pd.option_context("display.max_columns", None, "display.width", 220):
        print(_df[show_cols].tail(5).to_string(index=False))
else:
    print("No trades in any symbol.")

XLMUSDT  columns: ['symbol', 'orderType', 'leverage', 'updatedTime', 'side', 'orderId', 'closedPnl', 'openFee', 'closeFee', 'avgEntryPrice', 'qty', 'cumEntryValue', 'createdTime', 'orderPrice', 'closedSize', 'avgExitPrice', 'execType', 'fillCount', 'cumExitValue', 'entry_time', 'exit_time', 'position', 'notional_usdt', 'margin_usdt', 'roi_pct', 'price_move_pct']

                      entry_time                        exit_time position  leverage  avgEntryPrice  avgExitPrice  notional_usdt  margin_usdt  closedPnl  roi_pct  price_move_pct orderType
2026-05-31 12:00:14.858000+00:00 2026-06-02 15:03:47.971000+00:00     Long         1        0.26330       0.22029       120.5914     120.5914 -19.780290  -16.403         -16.403    Market
2026-06-03 08:00:14.722000+00:00 2026-06-03 19:51:37.751000+00:00     Long         1        0.22979       0.21427       293.4418     293.4418 -20.159256   -6.870          -6.870    Market

In [100]:
# SECTION 5 — Last LOOKBACK_DAYS on M5: price + trades (one figure per symbol)
_now_ms = int(time.time() * 1000)
chart_t0 = _now_ms - LOOKBACK_DAYS * DAY_MS
chart_t1 = _now_ms
_cutoff = pd.to_datetime(chart_t0, unit="ms", utc=True)

for symbol in SYMBOLS:
    trades = trade_frames.get(symbol, pd.DataFrame())
    if not trades.empty:
        trades = trades.loc[trades["exit_time"] >= _cutoff].copy()

    print(
        f"OHLCV {symbol}  {pd.to_datetime(chart_t0, unit='ms', utc=True)} .. "
        f"{pd.to_datetime(chart_t1, unit='ms', utc=True)} UTC"
    )
    ohlcv = fetch_klines_in_range(symbol, CHART_INTERVAL, chart_t0, chart_t1)
    if not ohlcv.empty:
        ohlcv.index = ohlcv.index.tz_convert(_TEHRAN)

    plot_symbol_trades(symbol, ohlcv, trades)

print("All charts rendered.")

OHLCV XLMUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV BTCUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV BCHUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV ETHUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV BNBUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV XRPUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV ADAUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV SOLUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV DOGEUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV DOTUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV AVAXUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV SHIB1000USDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

OHLCV LTCUSDT  2026-05-29 18:25:22.608000+00:00 .. 2026-06-06 18:25:22.608000+00:00 UTC

All charts rendered.

## Account summary — total P&L and wallet balance

Closed P&L is summed from all trades fetched in **Section 4** (up to `EFFECTIVE_CLOSED_PNL_DAYS`). Wallet balance is read live from Bybit.

In [101]:
# SECTION 6 — Closed P&L, leverage, and the capital metrics that actually matter

QUOTE_COIN = "USDT"
ACCOUNT_TYPE = "UNIFIED"


def _parse_wallet_usdt(resp: dict) -> dict:
    if resp.get("retCode") != 0:
        raise RuntimeError(f"Bybit {resp.get('retCode')}: {resp.get('retMsg')}")
    accounts = (resp.get("result") or {}).get("list") or []
    if not accounts:
        raise RuntimeError("Empty wallet balance response")
    coins = accounts[0].get("coin") or []
    usdt = next((c for c in coins if c.get("coin") == QUOTE_COIN), None)
    if usdt is None:
        return {"equity": 0.0, "wallet_balance": 0.0, "available": 0.0, "used_margin": 0.0}
    wallet_bal = float(usdt.get("walletBalance", 0) or 0)
    position_im = float(usdt.get("totalPositionIM", 0) or 0)
    order_im = float(usdt.get("totalOrderIM", 0) or 0)
    available = max(wallet_bal - position_im - order_im, 0.0)
    return {
        "equity": float(usdt.get("equity", 0) or 0),
        "wallet_balance": wallet_bal,
        "available": available,
        "used_margin": position_im + order_im,
    }


def _pnl_summary_frames(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    rows = []
    for sym, df in frames.items():
        if df is None or df.empty or "closedPnl" not in df.columns:
            rows.append({"symbol": sym, "trades": 0, "wins": 0, "losses": 0,
                         "avg_lev": 0.0, "margin_sum": 0.0, "closed_pnl": 0.0, "roi_pct": 0.0})
            continue
        pnls = pd.to_numeric(df["closedPnl"], errors="coerce").fillna(0.0)
        margin = pd.to_numeric(df.get("margin_usdt", 0.0), errors="coerce").fillna(0.0)
        lev = pd.to_numeric(df.get("leverage", 1.0), errors="coerce").fillna(1.0)
        tot_margin = float(margin.sum())  # cumulative margin TURNOVER, not capital
        rows.append({
            "symbol": sym,
            "trades": len(pnls),
            "wins": int((pnls > 0).sum()),
            "losses": int((pnls < 0).sum()),
            "avg_lev": round(float(lev.mean()), 1) if len(lev) else 0.0,
            "margin_sum": round(tot_margin, 2),
            "closed_pnl": round(float(pnls.sum()), 4),
            "roi_pct": round(float(pnls.sum()) / tot_margin * 100, 2) if tot_margin else 0.0,
        })
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    tot_margin_all = float(out["margin_sum"].sum())
    tot_pnl_all = float(out["closed_pnl"].sum())
    tt = int(out["trades"].sum())
    avg_lev_all = round(float((out["avg_lev"] * out["trades"]).sum() / tt), 1) if tt else 0.0
    total = pd.DataFrame([{
        "symbol": "ALL",
        "trades": tt,
        "wins": int(out["wins"].sum()),
        "losses": int(out["losses"].sum()),
        "avg_lev": avg_lev_all,
        "margin_sum": round(tot_margin_all, 2),
        "closed_pnl": round(tot_pnl_all, 4),
        "roi_pct": round(tot_pnl_all / tot_margin_all * 100, 2) if tot_margin_all else 0.0,
    }])
    return pd.concat([out, total], ignore_index=True)


def _peak_concurrent_margin(frames: dict[str, pd.DataFrame]) -> float:
    """Max total margin locked at any single instant = real capital the bot needed.

    Walks an event timeline (+margin at entry, -margin at exit) and tracks the
    running maximum. This is the honest 'how much money do I need' number — unlike
    the SUM of per-trade margins, which just measures reused-capital turnover.
    """
    events = []
    for df in frames.values():
        if df is None or df.empty or "margin_usdt" not in df.columns:
            continue
        if "entry_time" not in df.columns or "exit_time" not in df.columns:
            continue
        for _, r in df.iterrows():
            m = float(pd.to_numeric(r.get("margin_usdt"), errors="coerce") or 0.0)
            if m <= 0:
                continue
            events.append((r["entry_time"], +m))
            events.append((r["exit_time"], -m))
    if not events:
        return 0.0
    events.sort(key=lambda x: x[0])
    cur = peak = 0.0
    for _, delta in events:
        cur += delta
        peak = max(peak, cur)
    return peak


# ── Closed P&L (all symbols, full fetch window) ─────────────────────────────
pnl_by_symbol = _pnl_summary_frames(trade_frames)
total_row = pnl_by_symbol.loc[pnl_by_symbol["symbol"] == "ALL"].iloc[0] if not pnl_by_symbol.empty else None

print(f"Closed P&L window: last {EFFECTIVE_CLOSED_PNL_DAYS} day(s)  |  endpoint: {_mode}")
if total_row is not None:
    wr = (total_row["wins"] / total_row["trades"] * 100) if total_row["trades"] else 0.0
    print(
        f"Total: {int(total_row['trades'])} trades  |  "
        f"{int(total_row['wins'])}W / {int(total_row['losses'])}L  |  "
        f"win rate {wr:.1f}%  |  "
        f"net closed P&L: {total_row['closed_pnl']:+,.4f} {QUOTE_COIN}"
    )
    print(
        f"Avg per-trade return on margin: {total_row['roi_pct']:+.2f}% (margin-weighted)  |  "
        f"avg leverage {total_row['avg_lev']:g}x"
    )
    print("  note: this % is small because leverage=1 makes margin ~= full notional "
          "(~100x the ~20 USDT risk/trade). See the R / peak-capital metrics below.")

pnl_show = pnl_by_symbol.copy()
pnl_show["closed_pnl"] = pnl_show["closed_pnl"].map(lambda x: f"{x:+,.4f}")
pnl_show["roi_pct"]    = pnl_show["roi_pct"].map(lambda x: f"{x:+.2f}%")
pnl_show["avg_lev"]    = pnl_show["avg_lev"].map(lambda x: f"{x:g}x")
pnl_show["margin_sum"] = pnl_show["margin_sum"].map(lambda x: f"{x:,.2f}")
display(pnl_show)

# ── Wallet balance (live) ───────────────────────────────────────────────────
wallet_resp = client.get_wallet_balance(accountType=ACCOUNT_TYPE, coin=QUOTE_COIN)
wallet = _parse_wallet_usdt(wallet_resp)

wallet_df = pd.DataFrame([{
    "equity": f"{wallet['equity']:,.2f}",
    "wallet_balance": f"{wallet['wallet_balance']:,.2f}",
    "available": f"{wallet['available']:,.2f}",
    "used_margin": f"{wallet['used_margin']:,.2f}",
}])
print(f"\nWallet ({ACCOUNT_TYPE}, {QUOTE_COIN}):")
display(wallet_df)

# ── Capital & return — the metrics that actually matter ─────────────────────
_nonempty = [d for d in trade_frames.values() if d is not None and not d.empty]
if _nonempty and total_row is not None:
    _allp = pd.concat(_nonempty, ignore_index=True)
    pnl_all = float(pd.to_numeric(_allp["closedPnl"], errors="coerce").fillna(0.0).sum())
    peak_margin = _peak_concurrent_margin(trade_frames)
    losers = pd.to_numeric(_allp["closedPnl"], errors="coerce")
    losers = losers[losers < 0].abs()
    risk_est = float(losers.median()) if len(losers) else 0.0

    print("\nCapital & return (what actually matters):")
    print(f"  Peak concurrent margin used : {peak_margin:,.0f} {QUOTE_COIN}"
          f"   <- real capital needed at once (avg leverage {total_row['avg_lev']:g}x)")
    print(f"  Total margin TURNOVER       : {total_row['margin_sum']:,.0f} {QUOTE_COIN}"
          f"   (sum of all {int(total_row['trades'])} trades' margin; reused capital, NOT money you had)")
    print(f"  Net P&L                     : {pnl_all:+,.2f} {QUOTE_COIN}")
    if peak_margin:
        print(f"  Return on peak capital      : {pnl_all / peak_margin * 100:+.2f}%")
    if wallet["equity"]:
        print(f"  Return on account equity    : {pnl_all / wallet['equity'] * 100:+.2f}%")
    if risk_est:
        print(f"  Total in R (risk ~{risk_est:.0f}/trade): {pnl_all / risk_est:+.1f}R "
              f"over {int(total_row['trades'])} trades")

Closed P&L window: last 8 day(s)  |  endpoint: demo
Total: 115 trades  |  47W / 68L  |  win rate 40.9%  |  net closed P&L: +623.0872 USDT
Avg per-trade return on margin: +0.30% (margin-weighted)  |  avg leverage 1x
  note: this % is small because leverage=1 makes margin ~= full notional (~100x the ~20 USDT risk/trade). See the R / peak-capital metrics below.

          symbol  trades  wins  losses avg_lev  margin_sum closed_pnl roi_pct
0        XLMUSDT       2     0       2      1x      414.03   -39.9395  -9.65%
1        BTCUSDT       0     0       0      0x        0.00    +0.0000  +0.00%
2        BCHUSDT       3     3       0      1x    1,475.19  +131.5868  +8.92%
3        ETHUSDT       3     3       0      1x    2,109.06  +131.5119  +6.24%
4        BNBUSDT       0     0       0      0x        0.00    +0.0000  +0.00%
5        XRPUSDT       4     4       0      1x    4,000.79  +104.0605  +2.60%
6        ADAUSDT      20     8      12      1x   32,607.90  +115.7484  +0.35%
7        SOLUSDT      19     7      12      1x   41,625.87   +65.3304  +0.16%
8       DOGEUSDT      17     4      13      1x   35,518.78  -101.8851  -0.29%
9        DOTUSDT       8     3       5      1x    9,527.28   +39.9329  +0.42%
10      AVAXUSDT      25     9      16      1x   53,416.44   +68.7492  +0.13%
11  SHIB1000USDT      12     4       8      1x   27,962.71    +8.9932  +0.03%
12       LTCUSDT       2     2       0      1x    1,361.03   +98.9985  +7.27%
13           ALL     115    47      68      1x  210,019.08  +623.0872  +0.30%

Wallet (UNIFIED, USDT):

      equity wallet_balance  available used_margin
0  56,736.51      56,631.19  52,820.96    3,810.23

Capital & return (what actually matters):
  Peak concurrent margin used : 20,963 USDT   <- real capital needed at once (avg leverage 1x)
  Total margin TURNOVER       : 210,019 USDT   (sum of all 115 trades' margin; reused capital, NOT money you had)
  Net P&L                     : +623.09 USDT
  Return on peak capital      : +2.97%
  Return on account equity    : +1.10%
  Total in R (risk ~22/trade): +28.0R over 115 trades

## Last 20 closed trades — all key fields

Most recent 20 closed trades across all symbols, straight from the exchange's closed-P&L records, with every important parameter: side, entry/exit time & price, duration, leverage, notional, margin, fees, net P&L, ROI %, and exit type (TP/SL).

In [102]:
# SECTION 7 — Last 20 closed trades from the exchange (all key fields)
_nonempty = [d for d in trade_frames.values() if d is not None and not d.empty]
if _nonempty:
    _all = pd.concat(_nonempty, ignore_index=True).sort_values("exit_time")
    last20 = _all.tail(40).copy()

    # Local (Tehran) timestamps + duration in minutes
    last20["entry"]   = last20["entry_time"].dt.tz_convert(_TEHRAN).dt.strftime("%m-%d %H:%M")
    last20["exit"]    = last20["exit_time"].dt.tz_convert(_TEHRAN).dt.strftime("%m-%d %H:%M")
    last20["dur_min"] = ((last20["exit_time"] - last20["entry_time"]).dt.total_seconds() / 60).round(0).astype(int)

    # Exit type (TP / SL / manual) via the classifier from the helpers cell
    last20["exit_type"] = last20.apply(_classify_exit, axis=1)

    # Total round-trip fees and a clean quantity column
    last20["fees"] = (
        pd.to_numeric(last20.get("openFee", 0), errors="coerce").fillna(0.0)
        + pd.to_numeric(last20.get("closeFee", 0), errors="coerce").fillna(0.0)
    ).round(3)
    last20["qty"] = pd.to_numeric(last20.get("closedSize"), errors="coerce")

    cols = ["symbol", "position", "entry", "exit", "dur_min", "leverage",
            "avgEntryPrice", "avgExitPrice", "qty",
            "notional_usdt", "margin_usdt", "fees", "closedPnl",
            "roi_pct", "price_move_pct", "exit_type"]
    cols = [c for c in cols if c in last20.columns]
    table = last20[cols].rename(columns={
        "avgEntryPrice": "entry_px", "avgExitPrice": "exit_px", "closedPnl": "pnl",
    }).reset_index(drop=True)

    for c in ("notional_usdt", "margin_usdt"):
        if c in table.columns:
            table[c] = table[c].round(2)
    if "pnl" in table.columns:
        table["pnl"] = table["pnl"].round(3)

    print(f"Last {len(table)}/{len(_all)} closed trades (newest at bottom)  |  times in {_TEHRAN}  |  endpoint: {_mode}")
    display(table)
else:
    print("No closed trades to show.")

Last 40/115 closed trades (newest at bottom)  |  times in Asia/Tehran  |  endpoint: demo

,symbol,position,entry,exit,dur_min,leverage,entry_px,exit_px,qty,notional_usdt,margin_usdt,fees,pnl,roi_pct,price_move_pct,exit_type
0,AVAXUSDT,Short,06-03 15:50,06-04 00:15,506,1,8.255000,7.997000,189.50,1564.32,1564.32,1.694,47.298,3.024,3.024,TP
1,ADAUSDT,Short,06-02 19:05,06-04 00:23,1759,1,0.215300,0.201500,3654.00,786.71,786.71,0.838,49.620,6.307,6.307,TP
2,ETHUSDT,Short,06-02 18:55,06-04 00:25,1770,1,1917.970000,1772.780000,0.29,556.21,556.21,0.589,41.587,7.477,7.477,TP
3,AVAXUSDT,Short,06-04 00:20,06-04 01:18,58,1,7.972000,8.146000,116.90,931.93,931.93,1.036,-21.377,-2.294,-2.294,SL
4,DOGEUSDT,Short,06-02 17:55,06-04 03:59,2044,1,0.096710,0.090350,8092.00,782.58,782.58,0.833,50.632,6.470,6.470,TP
5,BCHUSDT,Short,06-01 15:00,06-04 04:53,3713,1,280.000000,233.000000,0.96,268.80,268.80,0.271,44.415,16.524,16.524,TP
6,SOLUSDT,Short,06-03 02:25,06-04 05:20,1615,1,73.790000,68.790000,10.00,737.90,737.90,0.784,48.971,6.636,6.636,TP
7,SHIB1000USDT,Short,06-02 18:00,06-04 05:23,2123,1,0.005326,0.004977,144860.00,771.52,771.52,0.821,49.813,6.456,6.456,TP
8,AVAXUSDT,Short,06-04 04:05,06-04 05:31,86,1,8.022000,7.735000,183.00,1468.03,1468.03,1.586,50.935,3.470,3.470,TP
9,DOTUSDT,Short,06-03 19:50,06-04 05:32,582,1,1.100300,1.036500,769.60,846.79,846.79,0.904,48.218,5.694,5.694,TP
10,XRPUSDT,Short,06-02 18:30,06-04 05:33,2103,1,1.235000,1.150300,356.50,440.28,440.28,0.468,29.675,6.740,6.740,TP
11,ADAUSDT,Short,06-04 00:25,06-04 05:33,308,1,0.201000,0.188800,3917.00,787.32,787.32,0.840,46.878,5.954,5.954,TP
12,SOLUSDT,Short,06-04 05:25,06-04 06:37,72,1,68.440000,70.970000,7.80,533.83,533.83,0.598,-20.332,-3.809,-3.809,SL
13,AVAXUSDT,Short,06-04 05:35,06-04 07:02,87,1,7.548000,8.032000,40.10,302.67,302.67,0.344,-19.752,-6.526,-6.526,SL
14,ADAUSDT,Short,06-04 05:35,06-04 07:03,88,1,0.188500,0.199000,1815.00,342.13,342.13,0.387,-19.444,-5.683,-5.683,SL
15,SHIB1000USDT,Short,06-04 05:25,06-04 07:13,109,1,0.004983,0.005146,124370.00,619.74,619.74,0.693,-20.965,-3.383,-3.383,SL
16,SOLUSDT,Short,06-04 08:30,06-04 11:41,192,1,70.790000,68.590000,22.10,1564.46,1564.46,1.694,46.722,2.986,2.986,TP
17,AVAXUSDT,Short,06-04 10:45,06-04 14:19,215,1,7.878000,7.573000,164.80,1298.29,1298.29,1.400,48.950,3.770,3.770,TP
18,AVAXUSDT,Short,06-04 14:20,06-04 15:53,94,1,7.594000,7.718000,154.70,1174.79,1174.79,1.303,-20.486,-1.744,-1.744,SL
19,SOLUSDT,Short,06-04 11:45,06-04 16:07,262,1,68.460000,70.110000,12.10,828.37,828.37,0.922,-20.887,-2.521,-2.521,SL
20,ADAUSDT,Short,06-04 10:50,06-04 19:58,548,1,0.195800,0.186000,5132.00,1004.85,1004.85,1.078,49.091,4.885,4.885,TP
21,ADAUSDT,Short,06-04 20:00,06-05 03:44,465,1,0.186700,0.175200,4426.00,826.33,826.33,0.881,49.895,6.038,6.038,TP
22,SHIB1000USDT,Short,06-04 10:40,06-05 06:12,1172,1,0.005032,0.004863,299360.00,1506.38,1506.38,1.629,48.465,3.217,3.217,TP
23,AVAXUSDT,Short,06-05 01:00,06-05 06:13,313,1,7.669000,7.435000,214.50,1645.00,1645.00,1.782,48.348,2.939,2.939,TP
24,SOLUSDT,Short,06-04 19:40,06-05 07:34,714,1,69.340000,66.400000,17.00,1178.78,1178.78,1.269,48.553,4.119,4.119,TP
25,SOLUSDT,Short,06-05 07:35,06-05 07:59,25,1,66.870000,67.880000,19.90,1330.71,1330.71,1.475,-21.574,-1.621,-1.621,SL
26,DOGEUSDT,Short,06-04 04:00,06-05 09:17,1757,1,0.090250,0.084820,9951.00,898.08,898.08,0.958,53.010,5.903,5.903,TP
27,SHIB1000USDT,Short,06-05 06:15,06-05 09:49,214,1,0.004860,0.004686,288970.00,1404.39,1404.39,1.517,48.764,3.472,3.472,TP
28,LTCUSDT,Short,06-02 18:30,06-05 09:52,3802,1,48.370000,43.300000,9.80,474.03,474.03,0.494,49.186,10.376,10.376,TP
29,AVAXUSDT,Short,06-05 06:15,06-05 17:31,677,1,7.465000,6.951000,97.70,729.33,729.33,0.775,49.482,6.785,6.785,TP
30,ADAUSDT,Short,06-05 03:45,06-05 18:45,900,1,0.176100,0.157500,2727.00,480.22,480.22,0.500,50.266,10.467,10.467,TP
31,ETHUSDT,Short,06-04 00:25,06-05 19:11,2566,1,1774.170000,1572.500000,0.21,372.58,372.58,0.387,41.965,11.263,11.263,TP
32,BCHUSDT,Short,06-04 04:55,06-05 19:40,2326,1,234.700000,211.900000,1.72,403.68,403.68,0.422,38.766,9.603,9.603,TP
33,ADAUSDT,Short,06-05 19:20,06-05 20:21,61,1,0.158200,0.162200,5171.00,818.05,818.05,0.911,-21.703,-2.653,-2.653,SL
34,SOLUSDT,Short,06-05 09:20,06-05 22:34,795,1,66.550000,62.370000,12.20,811.91,811.91,0.865,49.853,6.140,6.140,TP
35,ADAUSDT,Short,06-06 02:50,06-06 04:17,87,1,0.157300,0.161000,5393.00,848.32,848.32,0.944,-21.070,-2.484,-2.484,SL
36,DOGEUSDT,Short,06-05 09:35,06-06 08:01,1346,1,0.084770,0.078400,8055.00,682.82,682.82,0.723,50.651,7.418,7.418,TP
37,DOGEUSDT,Short,06-06 08:05,06-06 11:12,188,1,0.078310,0.081490,5995.00,469.47,469.47,0.527,-19.591,-4.173,-4.173,SL
38,ADAUSDT,Short,06-06 06:35,06-06 11:51,316,1,0.154600,0.158500,5106.00,789.39,789.39,0.879,-20.787,-2.633,-2.633,SL
39,ADAUSDT,Short,06-06 14:05,06-06 16:51,166,1,0.154300,0.159500,3919.00,604.70,604.70,0.676,-21.055,-3.482,-3.482,SL

## Open positions & pending orders — live snapshot

Pulls **current open positions** (size > 0) directly from Bybit and builds one fully-detailed row per position:

- **entry / now / SL / TP / liq** prices, **size**, **leverage**
- **uPnL$** — unrealised P&L in USDT · **ROI%** — on locked margin · **move%** — raw price move from entry (in the trade's favour)
- **→SL% / →TP%** — distance from the **current** price to each barrier, as a % of price now
- **RR** — planned Risk:Reward `|TP-entry| / |entry-SL|` · **risk$ / reward$** — USDT lost if SL hits / gained if TP hits
- **R_done** — how much of the planned R-distance the price has already travelled · **age** · **state** (📈/📉 + ⚠ flags for mis-placed or missing SL/TP)

A second table lists **pending (un-filled) entry / conditional orders**. Re-run this cell any time for a fresh snapshot.

In [103]:
# SECTION 8 — Open positions & pending orders (live snapshot, full per-row detail)
# Pulls the CURRENT open positions (size > 0) straight from Bybit and builds one
# fully-detailed row per position:
#   entry / mark(now) / SL / TP prices, size, leverage, liq price
#   unrealised PnL (USDT) + ROI% on margin + raw price-move% from entry
#   distance from the CURRENT price to SL and to TP, in %
#   planned Risk:Reward (|TP-entry| / |entry-SL|) and the USDT risk / reward it implies
#   how far through that R the trade currently is, plus position age
# A second table lists pending (un-filled) entry / conditional orders, each linked
# to its parent position with the fill price, current price and profit/loss state.
# Bybit /v5/order/realtime for category=linear returns ALL order kinds by default
# (active + conditional/StopOrder), so pending conditional exits show up too.

import math


def _to_f(x, default=float("nan")):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


def _fmt_px(x) -> str:
    """Adaptive price formatting — copes with BTC (~100k) and SHIB (~0.004) alike."""
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    ax = abs(x)
    d = 2 if ax >= 1000 else 4 if ax >= 1 else 5 if ax >= 0.01 else 6
    return f"{x:,.{d}f}"


def fetch_open_positions() -> list[dict]:
    """All open positions for the settle coin (handles pagination)."""
    out, cursor = [], None
    while True:
        kwargs = dict(category=CATEGORY, settleCoin=QUOTE_COIN, limit=200)
        if cursor:
            kwargs["cursor"] = cursor
        resp = client.get_positions(**kwargs)
        if resp.get("retCode") != 0:
            raise RuntimeError(f"Bybit {resp.get('retCode')}: {resp.get('retMsg')}")
        result = resp["result"]
        out.extend(result.get("list") or [])
        cursor = result.get("nextPageCursor") or ""
        if not cursor:
            break
        time.sleep(0.06)
    return [p for p in out if _to_f(p.get("size"), 0.0) != 0.0]  # live positions only


def fetch_pending_orders() -> list[dict]:
    """Open (un-filled) limit / conditional orders for the settle coin.

    No `orderFilter` is passed: for linear, Bybit returns every order kind by
    default (active + conditional). `openOnly=0` keeps only open-status orders.
    """
    out, cursor = [], None
    while True:
        kwargs = dict(category=CATEGORY, settleCoin=QUOTE_COIN, limit=50, openOnly=0)
        if cursor:
            kwargs["cursor"] = cursor
        resp = client.get_open_orders(**kwargs)
        if resp.get("retCode") != 0:
            raise RuntimeError(f"Bybit {resp.get('retCode')}: {resp.get('retMsg')}")
        result = resp["result"]
        out.extend(result.get("list") or [])
        cursor = result.get("nextPageCursor") or ""
        if not cursor:
            break
        time.sleep(0.06)
    return out


def build_open_positions_table(positions: list[dict]) -> pd.DataFrame:
    now_ms = int(time.time() * 1000)
    rows = []
    for p in positions:
        side    = p.get("side", "")                    # Buy => Long, Sell => Short
        is_long = side == "Buy"
        sign    = 1.0 if is_long else -1.0
        entry   = _to_f(p.get("avgPrice"))
        mark    = _to_f(p.get("markPrice"))
        sl      = _to_f(p.get("stopLoss"));   sl = sl if sl and not math.isnan(sl) else float("nan")
        tp      = _to_f(p.get("takeProfit")); tp = tp if tp and not math.isnan(tp) else float("nan")
        size    = _to_f(p.get("size"))
        lev     = _to_f(p.get("leverage"), 1.0) or 1.0
        upnl    = _to_f(p.get("unrealisedPnl"), 0.0)
        liq     = _to_f(p.get("liqPrice"))
        notion  = _to_f(p.get("positionValue"), abs(entry * size))
        margin  = _to_f(p.get("positionIM"), (notion / lev if lev else notion))
        created = p.get("createdTime")

        # current price move from entry, in the trade's favour (signed)
        move_pct = (mark - entry) / entry * 100 * sign if entry else float("nan")
        roi_pct  = upnl / margin * 100 if margin else float("nan")

        # distance from the price RIGHT NOW to each barrier, as % of current price
        to_sl_pct = abs(mark - sl) / mark * 100 if (mark and not math.isnan(sl)) else float("nan")
        to_tp_pct = abs(tp - mark) / mark * 100 if (mark and not math.isnan(tp)) else float("nan")

        # planned Risk:Reward, measured from the entry
        risk_px   = abs(entry - sl) if not math.isnan(sl) else float("nan")
        reward_px = abs(tp - entry) if not math.isnan(tp) else float("nan")
        rr        = (reward_px / risk_px) if (risk_px and not math.isnan(risk_px)
                                              and not math.isnan(reward_px)) else float("nan")
        risk_usdt   = risk_px * size if not math.isnan(risk_px) else float("nan")
        reward_usdt = reward_px * size if not math.isnan(reward_px) else float("nan")

        # how much of the planned R-distance the price has already travelled
        r_progress = (mark - entry) * sign / risk_px if (risk_px and not math.isnan(risk_px)) else float("nan")

        # SL/TP placement sanity (long: SL<entry & TP>entry ; short: opposite)
        sl_ok = math.isnan(sl) or (sl < entry if is_long else sl > entry)
        tp_ok = math.isnan(tp) or (tp > entry if is_long else tp < entry)
        flags = ""
        if not sl_ok:       flags += "⚠SL"
        if not tp_ok:       flags += "⚠TP"
        if math.isnan(sl):  flags += "·noSL"
        if math.isnan(tp):  flags += "·noTP"

        age_h = (now_ms - int(created)) / 3_600_000 if created else float("nan")
        age = (f"{age_h/24:.1f}d" if age_h >= 24 else f"{age_h:.1f}h") if not math.isnan(age_h) else "—"

        rows.append({
            "symbol":  p.get("symbol"),
            "dir":     "Long" if is_long else "Short",
            "size":    size,
            "lev":     f"{lev:g}x",
            "entry":   _fmt_px(entry),
            "now":     _fmt_px(mark),
            "SL":      _fmt_px(sl),
            "TP":      _fmt_px(tp),
            "liq":     _fmt_px(liq),
            "uPnL$":   round(upnl, 2),
            "ROI%":    round(roi_pct, 2)  if not math.isnan(roi_pct)  else float("nan"),
            "move%":   round(move_pct, 2) if not math.isnan(move_pct) else float("nan"),
            "→SL%":    round(to_sl_pct, 2) if not math.isnan(to_sl_pct) else float("nan"),
            "→TP%":    round(to_tp_pct, 2) if not math.isnan(to_tp_pct) else float("nan"),
            "RR":      round(rr, 2)       if not math.isnan(rr)       else float("nan"),
            "risk$":   round(risk_usdt, 1)   if not math.isnan(risk_usdt)   else float("nan"),
            "reward$": round(reward_usdt, 1) if not math.isnan(reward_usdt) else float("nan"),
            "R_done":  round(r_progress, 2)  if not math.isnan(r_progress)  else float("nan"),
            "margin$": round(margin, 1),
            "age":     age,
            "state":   ("📈 profit" if upnl > 0 else "📉 loss" if upnl < 0 else "flat")
                       + (f"  {flags}" if flags else ""),
        })
    df = pd.DataFrame(rows)
    if not df.empty:
        df = df.sort_values("uPnL$", ascending=False).reset_index(drop=True)
    return df


# ── Fetch & build ───────────────────────────────────────────────────────────
_open_pos = fetch_open_positions()
open_pos_df = build_open_positions_table(_open_pos)

print(f"Open positions: {len(open_pos_df)}  |  endpoint: {_mode}  |  price 'now' = mark price")
if open_pos_df.empty:
    print("No open positions right now.")
else:
    try:
        styled = (open_pos_df.style
                  .map(lambda v: f"color: {'#2e7d32' if v > 0 else '#c62828' if v < 0 else 'gray'}",
                       subset=["uPnL$", "ROI%", "move%"])
                  .format({"uPnL$": "{:+,.2f}", "ROI%": "{:+.2f}", "move%": "{:+.2f}",
                           "→SL%": "{:.2f}", "→TP%": "{:.2f}", "RR": "{:.2f}",
                           "R_done": "{:.2f}", "risk$": "{:,.1f}", "reward$": "{:,.1f}",
                           "margin$": "{:,.1f}", "size": "{:g}"}, na_rep="—")
                  .set_caption("Open positions — live"))
        display(styled)
    except Exception:
        with pd.option_context("display.max_columns", None, "display.width", 260):
            print(open_pos_df.to_string(index=False))

    # ── Portfolio summary ────────────────────────────────────────────────────
    tot_upnl   = open_pos_df["uPnL$"].sum()
    tot_margin = open_pos_df["margin$"].sum()
    tot_risk   = open_pos_df["risk$"].sum(skipna=True)
    tot_reward = open_pos_df["reward$"].sum(skipna=True)
    n_long  = int((open_pos_df["dir"] == "Long").sum())
    n_short = int((open_pos_df["dir"] == "Short").sum())
    n_prof  = int((open_pos_df["uPnL$"] > 0).sum())
    n_loss  = int((open_pos_df["uPnL$"] < 0).sum())

    print(f"\nPortfolio: {n_long} long / {n_short} short  |  {n_prof} in profit / {n_loss} in loss")
    roi_txt = f"   (ROI on margin: {tot_upnl / tot_margin * 100:+.2f}%)" if tot_margin else ""
    print(f"Total unrealised PnL : {tot_upnl:+,.2f} {QUOTE_COIN}")
    print(f"Total margin locked  : {tot_margin:,.2f} {QUOTE_COIN}{roi_txt}")
    if pd.notna(tot_risk) and tot_risk:
        print(f"If every SL hits     : {-tot_risk:+,.1f} {QUOTE_COIN}")
    if pd.notna(tot_reward) and tot_reward:
        rr_txt = f"   (basket RR: {tot_reward / tot_risk:.2f})" if (pd.notna(tot_risk) and tot_risk) else ""
        print(f"If every TP hits     : {tot_reward:+,.1f} {QUOTE_COIN}{rr_txt}")

# ── Pending (un-filled) orders — linked to their parent position ──────────────
# Each conditional SL/TP shows WHICH position it will close, that position's fill
# (entry) price, the price right now, and whether the position sits in profit/loss.
# A 'StopLoss'/'TakeProfit' row with status=Untriggered & reduceOnly=True is an
# ARMED exit waiting to fire — the position is still OPEN, nothing is closed yet.
_pending = fetch_pending_orders()
if _pending:
    pos_ix = {}
    for p in _open_pos:                       # one-way mode: one position per symbol
        side = p.get("side", "")
        upnl = _to_f(p.get("unrealisedPnl"), 0.0)
        pos_ix[p.get("symbol")] = {
            "dir":   "Long" if side == "Buy" else "Short",
            "entry": _to_f(p.get("avgPrice")),
            "now":   _to_f(p.get("markPrice")),
            "upnl":  upnl,
            "state": "📈 profit" if upnl > 0 else "📉 loss" if upnl < 0 else "flat",
        }

    prows = []
    for o in _pending:
        sym  = o.get("symbol")
        pos  = pos_ix.get(sym, {})
        now  = pos.get("now", float("nan"))
        trig = _to_f(o.get("triggerPrice"))
        to_trig = (abs(trig - now) / now * 100
                   if (now and not math.isnan(now) and not math.isnan(trig)) else float("nan"))
        prows.append({
            "symbol":     sym,
            "pos":        pos.get("dir", "—"),                    # position this order belongs to
            "type":       (o.get("stopOrderType") or o.get("orderType") or ""),
            "side":       o.get("side"),
            "qty":        _to_f(o.get("qty")),
            "filled@":    _fmt_px(pos.get("entry", float("nan"))),  # position fill / entry price
            "now":        _fmt_px(now),                             # current price
            "trigger":    _fmt_px(trig),                            # level this order fires at
            "→trig%":     round(to_trig, 2) if not math.isnan(to_trig) else float("nan"),
            "reduceOnly": o.get("reduceOnly"),
            "status":     o.get("orderStatus"),
            "pos_uPnL$":  round(pos["upnl"], 2) if pos else float("nan"),
            "pos_state":  pos.get("state", "—"),                   # is that position in profit/loss?
        })
    pending_df = pd.DataFrame(prows).sort_values(["symbol", "type"]).reset_index(drop=True)
    print(f"\nPending / conditional orders: {len(pending_df)}"
          f"   (filled@ = parent position entry price; now = current price)")
    with pd.option_context("display.max_columns", None, "display.width", 260):
        display(pending_df)
else:
    print("\nNo pending / conditional orders.")

Open positions: 11  |  endpoint: demo  |  price 'now' = mark price
      symbol   dir     size lev    entry      now       SL       TP        liq  uPnL$  ROI%  move%  →SL%  →TP%   RR  risk$  reward$  R_done  margin$    age    state
    AVAXUSDT Short    67.50  1x   6.9320   6.6380   7.2260   6.1900   1,558.30  19.84  4.42   4.24  8.86  6.75 2.52   19.8     50.1    1.00    448.6  23.7d 📈 profit
     DOTUSDT Short   218.40  1x   1.0188  0.93410   1.1027  0.78220   480.5014  18.50  9.06   8.31 18.05 16.26 2.82   18.3     51.7    1.01    204.3 150.3d 📈 profit
SHIB1000USDT Short 95410.00  1x 0.004703 0.004519 0.004901 0.004167     1.1023  17.56  4.07   3.91  8.45  7.79 2.71   18.9     51.1    0.93    431.7  23.7d 📈 profit
     XRPUSDT Short   255.40  1x   1.1500   1.0818   1.2390   1.0433   411.1738  17.42  6.30   5.93 14.53  3.56 1.20   22.7     27.3    0.77    276.6  24.4d 📈 profit
     BNBUSDT Short     0.62  1x 599.8000 574.4500 631.6000 535.9000 169,505.90  15.72  4.41   4.23  9.95  6.71 2.01   19.7     39.6    0.80    356.6  24.3d 📈 profit
     XLMUSDT Short  1061.00  1x  0.21412  0.20711  0.23287  0.16690    98.9229   7.44  3.38   3.27 12.44 19.41 2.52   19.9     50.1    0.37    220.0 148.4d 📈 profit
     LTCUSDT Short     8.30  1x  42.9700  42.2100  46.7100  38.2900  12,661.19   6.31  1.80   1.77 10.66  9.29 1.25   31.0     38.8    0.20    350.7 169.3d 📈 profit
     SOLUSDT Short     6.60  1x  62.2100  61.7230  65.4200  54.8900  15,931.04   3.21  0.79   0.78  5.99 11.07 2.28   21.2     48.3    0.15    407.8 168.9d 📈 profit
     ETHUSDT Short     0.12  1x 1,581.12 1,556.34 1,757.12 1,206.53          —   2.97  1.59   1.57 12.90 22.48 2.13   21.1     45.0    0.14    187.0 146.5d 📈 profit
     BCHUSDT Short     0.69  1x 214.9000 214.2000 243.1000 141.9000 152,007.68   0.48  0.33   0.33 13.49 33.75 2.59   19.5     50.4    0.02    148.0  23.7d 📈 profit
    DOGEUSDT Short  9609.00  1x  0.08056  0.08099  0.08257  0.07529    10.9809  -4.13 -0.53  -0.53  1.95  7.04 2.62   19.3     50.6   -0.21    779.1  24.0d   📉 loss

Portfolio: 0 long / 11 short  |  10 in profit / 1 in loss
Total unrealised PnL : +105.32 USDT
Total margin locked  : 3,810.40 USDT   (ROI on margin: +2.76%)
If every SL hits     : -231.4 USDT
If every TP hits     : +503.0 USDT   (basket RR: 2.17)

Pending / conditional orders: 22   (filled@ = parent position entry price; now = current price)

          symbol    pos        type side       qty   filled@       now   trigger  →trig%  reduceOnly       status  pos_uPnL$ pos_state
0       AVAXUSDT  Short    StopLoss  Buy     67.50    6.9320    6.6380    7.2260    8.86        True  Untriggered      19.84  📈 profit
1       AVAXUSDT  Short  TakeProfit  Buy     67.50    6.9320    6.6380    6.1900    6.75        True  Untriggered      19.84  📈 profit
2        BCHUSDT  Short    StopLoss  Buy      0.69  214.9000  214.2000  243.1000   13.49        True  Untriggered       0.48  📈 profit
3        BCHUSDT  Short  TakeProfit  Buy      0.69  214.9000  214.2000  141.9000   33.75        True  Untriggered       0.48  📈 profit
4        BNBUSDT  Short    StopLoss  Buy      0.62  599.8000  574.4500  631.6000    9.95        True  Untriggered      15.72  📈 profit
5        BNBUSDT  Short  TakeProfit  Buy      0.62  599.8000  574.4500  535.9000    6.71        True  Untriggered      15.72  📈 profit
6       DOGEUSDT  Short    StopLoss  Buy   9609.00   0.08056   0.08099   0.08257    1.95        True  Untriggered      -4.13    📉 loss
7       DOGEUSDT  Short  TakeProfit  Buy   9609.00   0.08056   0.08099   0.07529    7.04        True  Untriggered      -4.13    📉 loss
8        DOTUSDT  Short    StopLoss  Buy    218.40    1.0188   0.93410    1.1027   18.05        True  Untriggered      18.50  📈 profit
9        DOTUSDT  Short  TakeProfit  Buy    218.40    1.0188   0.93410   0.78220   16.26        True  Untriggered      18.50  📈 profit
10       ETHUSDT  Short    StopLoss  Buy      0.12  1,581.12  1,556.34  1,757.12   12.90        True  Untriggered       2.97  📈 profit
11       ETHUSDT  Short  TakeProfit  Buy      0.12  1,581.12  1,556.34  1,206.53   22.48        True  Untriggered       2.97  📈 profit
12       LTCUSDT  Short    StopLoss  Buy      8.30   42.9700   42.2100   46.7100   10.66        True  Untriggered       6.31  📈 profit
13       LTCUSDT  Short  TakeProfit  Buy      8.30   42.9700   42.2100   38.2900    9.29        True  Untriggered       6.31  📈 profit
14  SHIB1000USDT  Short    StopLoss  Buy  95410.00  0.004703  0.004519  0.004901    8.45        True  Untriggered      17.56  📈 profit
15  SHIB1000USDT  Short  TakeProfit  Buy  95410.00  0.004703  0.004519  0.004167    7.79        True  Untriggered      17.56  📈 profit
16       SOLUSDT  Short    StopLoss  Buy      6.60   62.2100   61.7230   65.4200    5.99        True  Untriggered       3.21  📈 profit
17       SOLUSDT  Short  TakeProfit  Buy      6.60   62.2100   61.7230   54.8900   11.07        True  Untriggered       3.21  📈 profit
18       XLMUSDT  Short    StopLoss  Buy   1061.00   0.21412   0.20711   0.23287   12.44        True  Untriggered       7.44  📈 profit
19       XLMUSDT  Short  TakeProfit  Buy   1061.00   0.21412   0.20711   0.16690   19.41        True  Untriggered       7.44  📈 profit
20       XRPUSDT  Short    StopLoss  Buy    255.40    1.1500    1.0818    1.2390   14.53        True  Untriggered      17.42  📈 profit
21       XRPUSDT  Short  TakeProfit  Buy    255.40    1.1500    1.0818    1.0433    3.56        True  Untriggered      17.42  📈 profit

## Per-trade SL% / TP% distance + "was the TP too far?" diagnosis

The exchange's closed-P&L records **don't store the SL/TP** that were set, so for every
closed trade we read the **planned SL & TP from the bot's own logs**
(`logs/bybit_bot/<SYMBOL>-*.jsonl` → `signal` + `market_order_placed` events) and match
them to each trade by side + entry time. From the **actual entry fill** we then compute:

- **sl_pct** — distance entry → SL, as % of entry
- **tp_pct** — distance entry → TP, as % of entry
- **rr_real** = `tp_pct / sl_pct` (planned RR is 2.5; this is what the fill made it)
- **hit** — which level the exit price actually landed on (**SL** / **TP** / manual)

Then it tests the hypothesis *"the SL was hit because the TP was too far to reach"* by
comparing TP-distance for SL-hit vs TP-hit trades, and the TP-hit rate per TP-distance bucket.

In [ ]:
# SECTION 9 — Per-trade SL%/TP% (from the bot's logs) + "was the TP too far?" analysis
# The exchange closed-PnL rows carry no SL/TP, so we read the PLANNED levels from the
# bot's own JSONL logs (signal + market_order_placed) and attach them to each closed
# trade by side + entry time. Then we compute the entry->SL and entry->TP distances in
# %, and test whether SL hits are driven by the TP being placed too far away.

import json

BOT_LOG_DIR = _ROOT / "logs" / "bybit_bot"


def _num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def _pf(x) -> str:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "—"
    ax = abs(x)
    d = 2 if ax >= 1000 else 4 if ax >= 1 else 5 if ax >= 0.01 else 6
    return f"{x:,.{d}f}"


def load_logged_entries(symbol: str) -> pd.DataFrame:
    """One row per ENTRY (market_order_placed), with the planned entry/sl/tp/rr/side.
    `entry` comes from the `signal` event logged in the same cycle just before it."""
    rows, last_sig = [], None
    for fp in sorted(BOT_LOG_DIR.glob(f"{symbol}-*.jsonl")):
        try:
            with open(fp, encoding="utf-8") as f:
                for line in f:
                    if '"event"' not in line:
                        continue
                    try:
                        e = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    ev = e.get("event")
                    if ev == "signal":
                        last_sig = e
                    elif ev == "market_order_placed":
                        rows.append({
                            "log_ts":     pd.to_datetime(e.get("ts"), utc=True, errors="coerce"),
                            "log_side":   (e.get("side") or "").lower(),
                            "plan_entry": _num(last_sig.get("entry")) if last_sig else float("nan"),
                            "log_sl":     _num(e.get("sl")),
                            "log_tp":     _num(e.get("tp")),
                            "log_rr":     _num(e.get("rr")),
                        })
        except OSError:
            continue
    return pd.DataFrame(rows)


def attach_logged_sltp(trades: pd.DataFrame, symbol: str, tol_min: float = 180) -> pd.DataFrame:
    """Match each closed trade to the nearest logged entry of the SAME side; require the
    planned entry to agree with the fill within 5% so we never grab the wrong order."""
    trades = trades.copy()
    for c in ("plan_entry", "sl_planned", "tp_planned", "rr_planned"):
        trades[c] = float("nan")
    if trades.empty or "entry_time" not in trades.columns:
        return trades
    logs = load_logged_entries(symbol)
    if logs.empty:
        return trades
    logs = logs.dropna(subset=["log_ts"]).sort_values("log_ts").reset_index(drop=True)
    for i, tr in trades.iterrows():
        et = tr["entry_time"]
        want = "sell" if tr.get("position") == "Short" else ("buy" if tr.get("position") == "Long" else None)
        cand = logs[logs["log_side"] == want] if want else logs
        if cand.empty:
            continue
        dt = (cand["log_ts"] - et).abs()
        j = dt.idxmin()
        if dt.loc[j] > pd.Timedelta(minutes=tol_min):
            continue
        pe, fill = cand.at[j, "plan_entry"], _num(tr.get("avgEntryPrice"))
        if pd.notna(pe) and fill and abs(pe - fill) / fill > 0.05:
            continue  # entry prices disagree → not the same trade
        trades.at[i, "plan_entry"] = pe
        trades.at[i, "sl_planned"] = cand.at[j, "log_sl"]
        trades.at[i, "tp_planned"] = cand.at[j, "log_tp"]
        trades.at[i, "rr_planned"] = cand.at[j, "log_rr"]
    return trades


def classify_hit(r) -> str:
    """Which level did the exit price actually land on? (2% tolerance for slippage)"""
    ex, sl, tp = _num(r.get("avgExitPrice")), r.get("sl_planned"), r.get("tp_planned")
    if pd.isna(ex) or not ex:
        return "?"
    d_sl = abs(ex - sl) / ex if pd.notna(sl) else float("inf")
    d_tp = abs(ex - tp) / ex if pd.notna(tp) else float("inf")
    if min(d_sl, d_tp) <= 0.02:
        return "SL" if d_sl < d_tp else "TP"
    return "manual"


# ── Enrich every closed trade with planned SL/TP and the % distances ──────────
_frames = []
for _sym, _df in trade_frames.items():
    if _df is None or _df.empty:
        continue
    _frames.append(attach_logged_sltp(_df, _sym))

if not _frames:
    print("No closed trades to analyse.")
else:
    enr = pd.concat(_frames, ignore_index=True).sort_values("exit_time").reset_index(drop=True)
    enr["sl_pct"]  = (enr["sl_planned"] - enr["avgEntryPrice"]).abs() / enr["avgEntryPrice"] * 100
    enr["tp_pct"]  = (enr["tp_planned"] - enr["avgEntryPrice"]).abs() / enr["avgEntryPrice"] * 100
    enr["rr_real"] = enr["tp_pct"] / enr["sl_pct"]
    enr["hit"]     = enr.apply(classify_hit, axis=1)

    matched = int(enr["tp_pct"].notna().sum())
    print(f"Closed trades: {len(enr)}  |  matched to logged SL/TP: {matched}  "
          f"({matched/len(enr)*100:.0f}%)  |  endpoint: {_mode}")

    # ── Per-trade table — every trade with both SL% and TP% from entry ────────
    enr["entry_t"] = enr["entry_time"].dt.tz_convert(_TEHRAN).dt.strftime("%m-%d %H:%M")
    per_trade = pd.DataFrame({
        "symbol":  enr["symbol"],
        "pos":     enr["position"],
        "entry_t": enr["entry_t"],
        "entry":   enr["avgEntryPrice"].map(_pf),
        "exit":    enr["avgExitPrice"].map(_pf),
        "SL":      enr["sl_planned"].map(_pf),
        "TP":      enr["tp_planned"].map(_pf),
        "sl_pct":  enr["sl_pct"].round(2),
        "tp_pct":  enr["tp_pct"].round(2),
        "rr_real": enr["rr_real"].round(2),
        "hit":     enr["hit"],
        "pnl":     enr["closedPnl"].round(2),
    })
    print("\nEvery closed trade with entry→SL and entry→TP distance (%):")
    with pd.option_context("display.max_rows", 200, "display.max_columns", None, "display.width", 240):
        display(per_trade)

    # ── Hypothesis test: are SL hits caused by a too-far TP? ──────────────────
    m = enr.dropna(subset=["tp_pct", "sl_pct"]).copy()
    if not m.empty:
        by_hit = (m.groupby("hit")
                  .agg(trades=("tp_pct", "size"),
                       med_sl_pct=("sl_pct", "median"),
                       med_tp_pct=("tp_pct", "median"),
                       mean_tp_pct=("tp_pct", "mean"),
                       avg_pnl=("closedPnl", "mean"))
                  .round(2))
        print("\nBy exit outcome (median distances + avg PnL):")
        display(by_hit)

        m["tp_bucket"] = pd.cut(m["tp_pct"], bins=[0, 8, 15, 25, 1e9],
                                labels=["<8%", "8–15%", "15–25%", ">25%"])
        m["is_tp"] = (m["hit"] == "TP").astype(int)
        m["is_sl"] = (m["hit"] == "SL").astype(int)
        wr = (m.groupby("tp_bucket", observed=True)
              .agg(trades=("is_tp", "size"),
                   tp_hit_rate=("is_tp", "mean"),
                   sl_hit_rate=("is_sl", "mean"),
                   avg_pnl=("closedPnl", "mean"))
              .round(3))
        wr["tp_hit_rate"] = (wr["tp_hit_rate"] * 100).round(1)
        wr["sl_hit_rate"] = (wr["sl_hit_rate"] * 100).round(1)
        wr["avg_pnl"] = wr["avg_pnl"].round(2)
        print("\nThe smoking gun — TP-hit vs SL-hit rate by how far the TP was placed:")
        display(wr)

        slh, tph = m[m["hit"] == "SL"], m[m["hit"] == "TP"]
        print("\nConclusion:")
        if len(slh) and len(tph):
            print(f"  • SL-hit trades: TP was a median {slh['tp_pct'].median():.1f}% away from entry")
            print(f"  • TP-hit trades: TP was a median {tph['tp_pct'].median():.1f}% away from entry")
            verdict = ("FARTHER" if slh['tp_pct'].median() > tph['tp_pct'].median() else "NOT farther")
            print(f"  → On the trades that got stopped out, the TP was {verdict} than on the winners,"
                  f"\n    supporting the idea that unreachable TPs let price reverse into the SL."
                  if verdict == "FARTHER" else
                  f"  → TP distance does NOT look like the main driver of SL hits here.")

        # ── The actual SL-hit trades, worst (farthest TP) first ──────────────
        sl_list = (m[m["hit"] == "SL"]
                   .sort_values("tp_pct", ascending=False)
                   [["symbol", "position", "entry_t", "sl_pct", "tp_pct", "rr_real", "closedPnl"]]
                   .rename(columns={"closedPnl": "pnl"}).reset_index(drop=True))
        sl_list["pnl"] = sl_list["pnl"].round(2)
        print(f"\nAll SL-hit trades ({len(sl_list)}), farthest TP first:")
        with pd.option_context("display.max_rows", 200, "display.width", 200):
            display(sl_list)
    else:
        print("\nNo trades could be matched to logged SL/TP — cannot run the distance analysis.")